language: cpp

dist: bionic

jobs:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-10
            - g++-10
      before_install: export CXX=g++-10
      script:
        - cmake --version
        - mkdir build
        - cd build
        - cmake ..
        - cmake --build . --config Debug
        - ctest -C Debug

    - os: windows
      script:
        - cmake --version
        - mkdir build
        - cd build
        - cmake .. -G "Visual Studio 16 2019" -A x64
        - cmake --build . --config Debug
        - ctest -C Debug
